/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status de todos os agentes */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um agente (501 se ainda for stub) */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuração completa de um agente (parâmetros estáticos; funciona para stubs) */
        get: operations["get_agent_config_v1_agents__agent_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza parâmetros de um agente */
        patch: operations["patch_agent_config_v1_agents__agent_id__config_patch"];
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed em tempo real de alertas (SSE) */
        get: operations["stream_alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza thresholds do behavioral guard */
        patch: operations["patch_alerts_config_v1_alerts_config_patch"];
        trace?: never;
    };
    "/v1/alerts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico paginado de alertas */
        get: operations["list_alerts_history_v1_alerts_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtest/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Polling do resultado de um job de backtest */
        get: operations["get_job_v1_backtest_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtest/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulação de Monte Carlo sobre os trades do histórico */
        post: operations["run_montecarlo_v1_backtest_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia um backtest assíncrono; retorna job_id para polling */
        post: operations["run_backtest_v1_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtest/walkforward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Walk-forward validation — detecta overfitting */
        post: operations["run_walkforward_v1_backtest_walkforward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configurações gerais do sistema */
        get: operations["get_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza configurações gerais (in-memory para MVP) */
        patch: operations["patch_config_v1_config_patch"];
        trace?: never;
    };
    "/v1/hitl/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuração atual de autonomia (HITL) */
        get: operations["get_hitl_config_v1_hitl_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera o nível de autonomia (0-3) */
        patch: operations["update_hitl_config_v1_hitl_config_patch"];
        trace?: never;
    };
    "/v1/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista registros do diário (paginado) */
        get: operations["list_entries_v1_journal_get"];
        put?: never;
        /** Cria novo registro no diário */
        post: operations["create_entry_v1_journal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journal/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas do diário (win-rate por emoção, correlação disciplina, win-rate real) */
        get: operations["get_metrics_v1_journal_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OHLCV candles para o par (dry-run = sintético) */
        get: operations["get_candles_v1_market__pair__candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores técnicos (RSI, MACD, BB, ATR, MAs, Stoch) */
        get: operations["get_indicators_v1_market__pair__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suporte/Resistência e níveis de Fibonacci */
        get: operations["get_levels_v1_market__pair__levels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Padrões gráficos detectados (H&S, Double Top/Bottom, Triangles) */
        get: operations["get_patterns_v1_market__pair__patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regime de mercado atual (sideways | uptrend | downtrend | chaotic) */
        get: operations["get_regime_v1_market__pair__regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sinal de trading atual (buy/sell/hold) baseado em indicadores */
        get: operations["get_signal_v1_market__pair__signal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/{pair}/volume-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume Profile (POC, VAH, VAL, LVN) */
        get: operations["get_volume_profile_v1_market__pair__volume_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs do portfólio (Sharpe, Win Rate, Max Drawdown, ...) */
        get: operations["get_metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Série temporal de capital e drawdown (derivada do ledger) */
        get: operations["get_equity_v1_metrics_equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista ordens (filtra por status/par) */
        get: operations["list_orders_v1_orders_get"];
        put?: never;
        /** Submete uma ordem (202 se pendente de HITL, 201 se auto-aprovada) */
        post: operations["create_order_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Operador aprova ou rejeita uma ordem pendente (ação HITL) */
        patch: operations["decide_order_v1_orders__order_id__status_patch"];
        trace?: never;
    };
    "/v1/process/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event log (XES) das transições de processo */
        get: operations["list_process_events_v1_process_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk/circuit-breaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status do circuit breaker */
        get: operations["get_circuit_breaker_v1_risk_circuit_breaker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parâmetros de risco (lê risk_params.yaml) */
        get: operations["get_risk_config_v1_risk_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza parâmetros de risco (grava em risk_params.yaml) */
        patch: operations["patch_risk_config_v1_risk_config_patch"];
        trace?: never;
    };
    "/v1/risk/kelly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Critério de Kelly — f*, fracionado e risco de ruína */
        get: operations["get_kelly_v1_risk_kelly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk/protections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proteções de drawdown (diário / semanal / mensal) */
        get: operations["get_protections_v1_risk_protections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIResponse[AgentConfigOut] */
        APIResponse_AgentConfigOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["AgentConfigOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[AgentStatusOut] */
        APIResponse_AgentStatusOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["AgentStatusOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[BacktestJobOut] */
        APIResponse_BacktestJobOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["BacktestJobOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[CircuitBreakerOut] */
        APIResponse_CircuitBreakerOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["CircuitBreakerOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[ConfigOut] */
        APIResponse_ConfigOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["ConfigOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[Dict[str, float]] */
        APIResponse_Dict_str__float__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: {
                [key: string]: number;
            };
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[HITLConfigOut] */
        APIResponse_HITLConfigOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["HITLConfigOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[IndicatorsOut] */
        APIResponse_IndicatorsOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["IndicatorsOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[JournalEntryOut] */
        APIResponse_JournalEntryOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["JournalEntryOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[JournalMetricsOut] */
        APIResponse_JournalMetricsOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["JournalMetricsOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[KellyOut] */
        APIResponse_KellyOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["KellyOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[LevelsOut] */
        APIResponse_LevelsOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["LevelsOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[AgentStatusOut]] */
        APIResponse_List_AgentStatusOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["AgentStatusOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[CandleOut]] */
        APIResponse_List_CandleOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["CandleOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[EquityPoint]] */
        APIResponse_List_EquityPoint__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["EquityPoint"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[JournalEntryOut]] */
        APIResponse_List_JournalEntryOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["JournalEntryOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[OrderOut]] */
        APIResponse_List_OrderOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["OrderOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[PatternOut]] */
        APIResponse_List_PatternOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["PatternOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[ProcessEventOut]] */
        APIResponse_List_ProcessEventOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["ProcessEventOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[List[ProtectionOut]] */
        APIResponse_List_ProtectionOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["ProtectionOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[MonteCarloOut] */
        APIResponse_MonteCarloOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["MonteCarloOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[OrderOut] */
        APIResponse_OrderOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["OrderOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[PortfolioMetricsOut] */
        APIResponse_PortfolioMetricsOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["PortfolioMetricsOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[RegimeOut] */
        APIResponse_RegimeOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["RegimeOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[RiskConfigOut] */
        APIResponse_RiskConfigOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["RiskConfigOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[SignalOut] */
        APIResponse_SignalOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["SignalOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[VolumeProfileOut] */
        APIResponse_VolumeProfileOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["VolumeProfileOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[WalkForwardOut] */
        APIResponse_WalkForwardOut_: {
            _links?: components["schemas"]["Links"] | null;
            data: components["schemas"]["WalkForwardOut"];
            meta?: components["schemas"]["Meta"] | null;
        };
        /** APIResponse[list[AlertOut]] */
        APIResponse_list_AlertOut__: {
            _links?: components["schemas"]["Links"] | null;
            /** Data */
            data: components["schemas"]["AlertOut"][];
            meta?: components["schemas"]["Meta"] | null;
        };
        /**
         * AgentConfigOut
         * @description Full agent detail including all static configurable parameters.
         */
        AgentConfigOut: {
            /** Cycles */
            cycles: number;
            /** Description */
            description: string;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Implemented */
            implemented: boolean;
            /** Last Action At */
            last_action_at?: string | null;
            /** Params */
            params?: Record<string, never>;
            /** Status */
            status: string;
        };
        /** AgentStatusOut */
        AgentStatusOut: {
            /** Cycles */
            cycles: number;
            /** Description */
            description: string;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Implemented */
            implemented: boolean;
            /** Last Action At */
            last_action_at?: string | null;
            /** Status */
            status: string;
        };
        /** AlertOut */
        AlertOut: {
            /** Agent Id */
            agent_id?: string | null;
            /** Auto Action */
            auto_action?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Occurred At */
            occurred_at: string;
            /** Pair */
            pair?: string | null;
            /** Severity */
            severity: string;
            /** Type */
            type: string;
        };
        /** AlertsConfigPatch */
        AlertsConfigPatch: {
            /** Euphoria Size Multiplier */
            euphoria_size_multiplier?: number | null;
            /** Overconfidence Margin */
            overconfidence_margin?: number | null;
            /** Revenge Size Multiplier */
            revenge_size_multiplier?: number | null;
            /** Risk Of Ruin Alert Pct */
            risk_of_ruin_alert_pct?: number | null;
        };
        /** AutonomyLevelOut */
        AutonomyLevelOut: {
            /** Description */
            description: string;
            /** Level */
            level: number;
            /** Threshold Usdt */
            threshold_usdt: number;
        };
        /** AutonomyLevelPatch */
        AutonomyLevelPatch: {
            /**
             * Confirm
             * @description Obrigatório confirm=true para escalar para autonomia total (nível 3)
             * @default false
             */
            confirm: boolean;
            /**
             * Level
             * @description Novo nível de autonomia (0-3)
             */
            level: number;
            /**
             * Operator
             * @description Quem alterou o nível
             * @default operator
             */
            operator: string;
            /**
             * Reason
             * @description Motivo da mudança de nível
             */
            reason: string;
        };
        /** BacktestConfigIn */
        BacktestConfigIn: {
            /**
             * Commission Pct
             * @default 0.1
             */
            commission_pct: number;
            /**
             * Initial Capital
             * @default 10000
             */
            initial_capital: number;
            /**
             * Monte Carlo Sims
             * @default 1000
             */
            monte_carlo_sims: number;
            /**
             * Pair
             * @default BTC/USDT
             */
            pair: string;
            /**
             * Slippage Bps
             * @default 5
             */
            slippage_bps: number;
            /**
             * Strategy
             * @default dca
             */
            strategy: string;
        };
        /** BacktestJobOut */
        BacktestJobOut: {
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            result?: components["schemas"]["BacktestResultOut"] | null;
            /** Status */
            status: string;
        };
        /** BacktestResultOut */
        BacktestResultOut: {
            /** Avg Loss Pct */
            avg_loss_pct: number;
            /** Avg Win Pct */
            avg_win_pct: number;
            /** Equity */
            equity: components["schemas"]["EquityPoint"][];
            /** Expectancy */
            expectancy: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Pnl Pct */
            pnl_pct: number;
            /** Pnl Usdt */
            pnl_usdt: number;
            /** Profit Factor */
            profit_factor: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Total Trades */
            total_trades: number;
            /** Win Rate */
            win_rate: number;
        };
        /** BollingerOut */
        BollingerOut: {
            /** Low */
            low: number;
            /** Mid */
            mid: number;
            /** Pct B */
            pct_b: number;
            /** Up */
            up: number;
        };
        /** CandleOut */
        CandleOut: {
            /** C */
            c: number;
            /** H */
            h: number;
            /** Lo */
            lo: number;
            /** O */
            o: number;
            /** T */
            t: number;
            /** V */
            v: number;
        };
        /** CircuitBreakerOut */
        CircuitBreakerOut: {
            /** Cooldown Hours */
            cooldown_hours: number;
            /** Cooldown Remaining */
            cooldown_remaining: number | null;
            /** Status */
            status: string;
            /** Triggers */
            triggers: string[];
        };
        /** ConfigOut */
        ConfigOut: {
            /** App Env */
            app_env: string;
            /** Autonomy Level */
            autonomy_level: number;
            /** Dry Run */
            dry_run: boolean;
            /** Exchange */
            exchange: string;
            /** Initial Capital */
            initial_capital: number;
            /** Orchestrator Interval Seconds */
            orchestrator_interval_seconds: number;
        };
        /** ConfigPatch */
        ConfigPatch: {
            /** Initial Capital */
            initial_capital?: number | null;
            /** Orchestrator Interval Seconds */
            orchestrator_interval_seconds?: number | null;
        };
        /** EmotionBand */
        EmotionBand: {
            /** Band */
            band: string;
            /** Trades */
            trades: number;
            /** Win Rate */
            win_rate: number;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Drawdown */
            drawdown: number;
            /** Equity */
            equity: number;
            /** T */
            t: string;
        };
        /** HITLConfigOut */
        HITLConfigOut: {
            /** Current Level */
            current_level: number;
            /** Human Approved Today */
            human_approved_today: number;
            /** Human Rejected Today */
            human_rejected_today: number;
            /** Last Changed At */
            last_changed_at?: string | null;
            /** Last Changed By */
            last_changed_by?: string | null;
            /** Level Description */
            level_description: string;
            /** Levels */
            levels: components["schemas"]["AutonomyLevelOut"][];
            /** Max Level */
            max_level: number;
            /** Min Level */
            min_level: number;
            /** Pending Orders Count */
            pending_orders_count: number;
            /** Threshold Usdt */
            threshold_usdt: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicatorsOut */
        IndicatorsOut: {
            /** Atr */
            atr: number | null;
            /** Atr Pct */
            atr_pct: number | null;
            bb: components["schemas"]["BollingerOut"] | null;
            /** Current Price */
            current_price: number | null;
            /** Ema21 */
            ema21: number | null;
            /** Ema9 */
            ema9: number | null;
            macd: components["schemas"]["MacdOut"] | null;
            /** Obv Trend */
            obv_trend: number | null;
            /** Rsi */
            rsi: number | null;
            /** Sma20 */
            sma20: number | null;
            /** Sma200 */
            sma200: number | null;
            /** Sma50 */
            sma50: number | null;
            stoch: components["schemas"]["StochOut"] | null;
            /** Volume Ratio */
            volume_ratio: number | null;
        };
        /** JournalEntryCreate */
        JournalEntryCreate: {
            /** Emotion After */
            emotion_after?: number | null;
            /** Emotion Before */
            emotion_before: number;
            /** Note */
            note?: string | null;
            /** Plan Followed */
            plan_followed: boolean;
            /** Pnl Pct */
            pnl_pct?: number | null;
            /** Setup */
            setup: string;
            /** Stop Defined */
            stop_defined: boolean;
        };
        /** JournalEntryOut */
        JournalEntryOut: {
            /** Created At */
            created_at: string;
            /** Emotion After */
            emotion_after?: number | null;
            /** Emotion Before */
            emotion_before: number;
            /** Id */
            id: number;
            /** Note */
            note?: string | null;
            /** Plan Followed */
            plan_followed: boolean;
            /** Pnl Pct */
            pnl_pct?: number | null;
            /** Setup */
            setup: string;
            /** Stop Defined */
            stop_defined: boolean;
        };
        /** JournalMetricsOut */
        JournalMetricsOut: {
            /** By Emotion */
            by_emotion: components["schemas"]["EmotionBand"][];
            /** Discipline Correlation */
            discipline_correlation: number | null;
            /** Plan Deviated Pnl */
            plan_deviated_pnl: number | null;
            /** Plan Followed Pnl */
            plan_followed_pnl: number | null;
            /** Real Win Rate */
            real_win_rate: number | null;
        };
        /** KellyOut */
        KellyOut: {
            /** Avg Loss Pct */
            avg_loss_pct?: number | null;
            /** Avg Win Pct */
            avg_win_pct?: number | null;
            /**
             * Data Quality
             * @default ok
             */
            data_quality: string;
            /** Fraction */
            fraction?: number | null;
            /** Fractional Kelly */
            fractional_kelly?: number | null;
            /** Full Kelly */
            full_kelly?: number | null;
            /** Risk Of Ruin */
            risk_of_ruin?: number | null;
            /** Trades */
            trades: number;
            /** Win Rate */
            win_rate?: number | null;
        };
        /** LevelsOut */
        LevelsOut: {
            /** Fib */
            fib: number[];
            /** Resistance */
            resistance: components["schemas"]["SRLevelOut"][];
            /** Support */
            support: components["schemas"]["SRLevelOut"][];
        };
        /** Links */
        Links: {
            /** Related */
            related?: Record<string, never> | null;
            /** Self */
            self: string;
        };
        /** MacdOut */
        MacdOut: {
            /** Hist */
            hist: number;
            /** Macd */
            macd: number;
            /** Signal */
            signal: number;
        };
        /** Meta */
        Meta: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Per Page
             * @default 20
             */
            per_page: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Total */
            total: number;
        };
        /** MonteCarloOut */
        MonteCarloOut: {
            /** Histogram */
            histogram: number[];
            /** Max Simulated Drawdown */
            max_simulated_drawdown: number;
            /** N */
            n: number;
            /** P5 */
            p5: number;
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** Profitable Pct */
            profitable_pct: number;
            /** Rejected */
            rejected: boolean;
        };
        /**
         * OrderCreate
         * @description Submit a new order. Validation makes it hard to use incorrectly.
         */
        OrderCreate: {
            /** Agent Id */
            agent_id: string;
            /** Confidence */
            confidence: number;
            /**
             * Critical
             * @description Força aprovação humana mesmo se dentro do limite
             * @default false
             */
            critical: boolean;
            /**
             * Pair
             * @example BTC/USDT
             */
            pair: string;
            /**
             * Position Size Pct
             * @description % do portfólio na posição
             */
            position_size_pct: number;
            /**
             * Price
             * @description Preço de referência/entrada (USDT)
             */
            price: number;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
            side: components["schemas"]["OrderSide"];
            /**
             * Stop Loss
             * @description Preço de stop loss (obrigatório)
             */
            stop_loss: number;
            /** Strategy */
            strategy: string;
            /**
             * Take Profit
             * @description Preço-alvo (opcional)
             */
            take_profit?: number | null;
        };
        /**
         * OrderDecisionPatch
         * @description Operator decision on a pending order (the core HITL action).
         */
        OrderDecisionPatch: {
            /** Decision */
            decision: string;
            /**
             * Operator
             * @default operator
             */
            operator: string;
            /** Operator Note */
            operator_note?: string | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Agent Id */
            agent_id: string;
            /** Auto Approved */
            auto_approved: boolean;
            /** Confidence */
            confidence: number;
            /** Created At */
            created_at: string;
            /** Critical */
            critical: boolean;
            /** Filled At */
            filled_at?: string | null;
            /** Id */
            id: string;
            /** Notional */
            notional: number;
            /** Operator Id */
            operator_id?: string | null;
            /** Operator Note */
            operator_note?: string | null;
            /** Pair */
            pair: string;
            /** Position Size Pct */
            position_size_pct?: number | null;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Rr */
            rr?: number | null;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Strategy */
            strategy: string;
            /** Take Profit */
            take_profit?: number | null;
        };
        /**
         * OrderSide
         * @enum {string}
         */
        OrderSide: "buy" | "sell";
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "approved" | "filled" | "rejected" | "cancelled";
        /** PatternOut */
        PatternOut: {
            /** Confidence */
            confidence: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Direction */
            direction: string;
            /** Name */
            name: string;
            /** Target */
            target: number | null;
        };
        /** PortfolioMetricsOut */
        PortfolioMetricsOut: {
            /** Calculated At */
            calculated_at: string;
            /** Exposure Pct */
            exposure_pct: number;
            /** Has Data */
            has_data: boolean;
            /** Initial Capital Usdt */
            initial_capital_usdt: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Open Positions */
            open_positions: number;
            /** Period */
            period: string;
            /** Pnl Period Pct */
            pnl_period_pct: number;
            /** Pnl Period Usdt */
            pnl_period_usdt: number;
            /** Portfolio Value Usdt */
            portfolio_value_usdt: number;
            /** Profit Factor */
            profit_factor: number | null;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Total Trades */
            total_trades: number;
            /** Win Rate */
            win_rate: number | null;
        };
        /** ProcessEventOut */
        ProcessEventOut: {
            /** Activity */
            activity: string;
            /** Actor */
            actor: string;
            /** Attributes */
            attributes?: Record<string, never>;
            /** Case Id */
            case_id: string;
            /** Timestamp */
            timestamp: string;
        };
        /** ProtectionOut */
        ProtectionOut: {
            /** Action */
            action: string;
            /** Limit */
            limit: number;
            /** Scope */
            scope: string;
            /** Status */
            status: string;
            /** Value */
            value: number;
        };
        /** RegimeOut */
        RegimeOut: {
            /** Active Strategies */
            active_strategies: string[];
            /** Confidence */
            confidence: number;
            /** Label */
            label: string;
            /** Regime */
            regime: string;
        };
        /** RiskConfigOut */
        RiskConfigOut: {
            /** Circuit Breaker Consecutive Losses */
            circuit_breaker_consecutive_losses: number;
            /** Circuit Breaker Enabled */
            circuit_breaker_enabled: boolean;
            /** Circuit Breaker Trigger Pct */
            circuit_breaker_trigger_pct: number;
            /** Cooldown Hours */
            cooldown_hours: number;
            /** Kelly Fraction */
            kelly_fraction: number;
            /** Max Daily Loss Pct */
            max_daily_loss_pct: number;
            /** Max Monthly Loss Pct */
            max_monthly_loss_pct: number;
            /** Max Position Size Pct */
            max_position_size_pct: number;
            /** Max Weekly Loss Pct */
            max_weekly_loss_pct: number;
            /** Min Position Size Pct */
            min_position_size_pct: number;
            /** Min Risk Reward Ratio */
            min_risk_reward_ratio: number;
            /** Stop Loss Default Pct */
            stop_loss_default_pct: number;
            /** Stop Loss Max Pct */
            stop_loss_max_pct: number;
            /** Take Profit Default Pct */
            take_profit_default_pct: number;
        };
        /** RiskConfigPatch */
        RiskConfigPatch: {
            /**
             * Confirm
             * @description Obrigatório confirm=true para gravar alterações de risco
             * @default false
             */
            confirm: boolean;
            /** Kelly Fraction */
            kelly_fraction?: number | null;
            /** Max Daily Loss Pct */
            max_daily_loss_pct?: number | null;
            /** Max Monthly Loss Pct */
            max_monthly_loss_pct?: number | null;
            /** Max Position Size Pct */
            max_position_size_pct?: number | null;
            /** Max Weekly Loss Pct */
            max_weekly_loss_pct?: number | null;
            /** Stop Loss Default Pct */
            stop_loss_default_pct?: number | null;
            /** Take Profit Default Pct */
            take_profit_default_pct?: number | null;
        };
        /** SRLevelOut */
        SRLevelOut: {
            /** Price */
            price: number;
            /** Strength */
            strength: number;
        };
        /** SignalOut */
        SignalOut: {
            /** Action */
            action: string;
            /** Confidence */
            confidence: number;
            /** Entry */
            entry: number;
            /** Position Size Pct */
            position_size_pct: number;
            /** Reason */
            reason: string;
            /** Rr */
            rr: number | null;
            /** Stop */
            stop: number | null;
            /** Strategy */
            strategy: string;
            /** Take Profit */
            take_profit: number | null;
        };
        /** StochOut */
        StochOut: {
            /** D */
            d: number;
            /** K */
            k: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumeProfileBin */
        VolumeProfileBin: {
            /** Pct */
            pct: number;
            /** Price */
            price: number;
            /** Volume */
            volume: number;
        };
        /** VolumeProfileOut */
        VolumeProfileOut: {
            /** Bins */
            bins: components["schemas"]["VolumeProfileBin"][];
            /** Lvn */
            lvn: number[];
            /** Poc */
            poc: number;
            /** Vah */
            vah: number;
            /** Val */
            val: number;
        };
        /** WalkForwardFold */
        WalkForwardFold: {
            /** Test Pnl Pct */
            test_pnl_pct: number;
            /** Test Sharpe */
            test_sharpe: number | null;
            /** Train Pnl Pct */
            train_pnl_pct: number;
            /** Train Sharpe */
            train_sharpe: number | null;
            /** Window Index */
            window_index: number;
        };
        /** WalkForwardOut */
        WalkForwardOut: {
            /** Folds */
            folds: components["schemas"]["WalkForwardFold"][];
            /** Sharpe Deviation */
            sharpe_deviation: number | null;
            /** Valid */
            valid: boolean;
            /** Windows */
            windows: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_agents_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_AgentStatusOut__"];
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AgentStatusOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_config_v1_agents__agent_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AgentConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_agent_config_v1_agents__agent_id__config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AgentConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_alerts_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: string | null;
                /** @description Quantos alertas recentes reenviar ao abrir */
                replay?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_alerts_config_v1_alerts_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertsConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_Dict_str__float__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_history_v1_alerts_history_get: {
        parameters: {
            query?: {
                severity?: string | null;
                since?: string | null;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_AlertOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_backtest_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_BacktestJobOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_montecarlo_v1_backtest_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_MonteCarloOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_v1_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_BacktestJobOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_walkforward_v1_backtest_walkforward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_WalkForwardOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ConfigOut_"];
                };
            };
        };
    };
    patch_config_v1_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hitl_config_v1_hitl_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_HITLConfigOut_"];
                };
            };
        };
    };
    update_hitl_config_v1_hitl_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutonomyLevelPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_HITLConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_v1_journal_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_JournalEntryOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_v1_journal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_JournalEntryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_v1_journal_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_JournalMetricsOut_"];
                };
            };
        };
    };
    get_candles_v1_market__pair__candles_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_CandleOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_indicators_v1_market__pair__indicators_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_IndicatorsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_levels_v1_market__pair__levels_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_LevelsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patterns_v1_market__pair__patterns_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_PatternOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regime_v1_market__pair__regime_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RegimeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signal_v1_market__pair__signal_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_SignalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_profile_v1_market__pair__volume_profile_get: {
        parameters: {
            query?: {
                tf?: string;
                limit?: number;
                bins?: number;
            };
            header?: never;
            path: {
                pair: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_VolumeProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_v1_metrics_get: {
        parameters: {
            query?: {
                period?: string;
                /** @description Filtrar por par (ex.: BTC/USDT). Vazio = portfólio inteiro. */
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_PortfolioMetricsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equity_v1_metrics_equity_get: {
        parameters: {
            query?: {
                period?: string;
                /** @description Filtrar por par (ex.: BTC/USDT). Vazio = portfólio inteiro. */
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_EquityPoint__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_v1_orders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["OrderStatus"] | null;
                pair?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_OrderOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_OrderOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_order_v1_orders__order_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderDecisionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_OrderOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_process_events_v1_process_events_get: {
        parameters: {
            query?: {
                /** @description Filtra por uma instância (order id) */
                case_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_ProcessEventOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_circuit_breaker_v1_risk_circuit_breaker_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_CircuitBreakerOut_"];
                };
            };
        };
    };
    get_risk_config_v1_risk_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RiskConfigOut_"];
                };
            };
        };
    };
    patch_risk_config_v1_risk_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RiskConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kelly_v1_risk_kelly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_KellyOut_"];
                };
            };
        };
    };
    get_protections_v1_risk_protections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_ProtectionOut__"];
                };
            };
        };
    };
}
